//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by 김호세 on 2023/04/01.
//

import Foundation
import ProjectDescription

let workspace = Workspace(
    name: "Application",
    projects: [
      "Projects/Application"
    ],
    generationOptions: .options(
      enableAutomaticXcodeSchemes: false,
      autogeneratedWorkspaceSchemes: .disabled,
      lastXcodeUpgradeCheck: nil,
      renderMarkdownReadme: false
    )
)
